[package]
name = "native-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.16.24" # Replace with the latest version
borsh = "0.10.3"           # Replace with the latest version

