[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "EnXiwvsvV9c9p2yggdvzaBuAuGAms2smeqQeyEZB7Zmy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nejc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
